### PR TITLE
Card 1204 add account notices

### PR DESCRIPTION
**Pull request by darushka**

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by mbebas** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by jsmylnycky** [comment]
please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/13388390f5813ff98208939bb568abd9530c1689

**Comment by jsmylnycky** [comment]
v0.5.3

**Pull request closed without merging**
