### PR TITLE
fixing alignment of buttons and sidenav

### PR DESCRIPTION
**Pull request by DarrylD**

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:  Simple enough.... pull the spacing fix I just put in and go ahead and merge --squash

**Comment by DarrylD** [comment]
@jsmylnycky S/M f6d6a9d422937042e55921cf4b9e1cfefd43d25c

**Comment by jsmylnycky** [comment]
@DarrylD Do you need this merged quickly for something else to pass, or can it wait until the other PRs get merged in?

**Comment by jsmylnycky** [comment]
v0.1.24

**Pull request closed without merging**
