### PR TITLE
Fix for 981 account logo stretched on latest version of Chrome

### PR DESCRIPTION
**Pull request by rwrzesien**

### CODE REVIEW

**Comment by jsmylnycky** [comment]
Have you verified that this isnt an issue in the mobile sidenav account image as well?

**Comment by rwrzesien** [comment]
@jsmylnycky Yes, it looks good there (same in Chrome as in FF, height was already set).

**Comment by jsmylnycky** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@rwrzesien please merge squash

**Comment by rwrzesien** [comment]
@jsmylnycky Merged and pushed, commit:
cf17c959ef228c273dd1a960f33c728987ce9b2c

**Comment by rynomars** [comment]
:+1:

**Comment by jsmylnycky** [comment]
v0.5.4

**Pull request closed without merging**
