### PR TITLE
removed underline form link

### PR DESCRIPTION
**Pull request by darushka**
This PR fixes bug https://whentomanage.atlassian.net/browse/CUST-1929.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
Does this have any affect on the sidenav styling? Pretty sure we use the md-list component there.

Otherwise: :+1:

**Comment by darushka** [comment]
As far as I understand out designes don't have links underlined. And sidenav mocks as well.

**Comment by darushka** [comment]
@jsmylnycky 
Can I merge this one?

**Comment by jsmylnycky** [comment]
@darushka Yeah, merge squash please

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/0ec493c9747a7792ae1f8ef18affe40d99be2004

**Comment by jsmylnycky** [comment]
Released v0.1.25

**Pull request closed without merging**
