### PR TITLE
Card 672 platform design cleanup

### PR DESCRIPTION
**Pull request by darushka**
This PR solves a bunch of issues on Platform design cleanup.

https://peachworks.leankit.com/Boards/View/267929177/286986138
https://peachworks.leankit.com/Boards/View/267929177/295545068

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by mbebas** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/4dcd1e0490e77ac4ae3e944531bc35fe88671721

**Comment by jsmylnycky** [comment]
v0.5.2

**Pull request closed without merging**
