### PR TITLE
Modal Cleanup

### PR DESCRIPTION
**Pull request by jsmylnycky**
Fixed padding of modal form input containers
Updated modals to support messages in header
Updated to support tab containers beneath the header, so it blends in.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
This ended up getting a bit more work, so putting back into QA

**Comment by darushka** [comment]
:+1:

**Comment by rwrzesien** [comment]
:+1:

**Comment by rynomars** [comment]
:thumbsup:

**Comment by jsmylnycky** [comment]
Released v0.3.6

**Pull request closed without merging**
