### PR TITLE
Design bugs and Material Datepicker background hotfix

### PR DESCRIPTION
**Pull request by darushka**
Added spacing to form elements according to issue https://whentomanage.atlassian.net/browse/CUST-1991.

### CODE REVIEW

**Comment by mbebas** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@darushka  Can you please add https://whentomanage.atlassian.net/browse/CUST-2166 into this PR? It should be a one liner and will solve a pretty big issue with alerts and their layout.

**Comment by darushka** [comment]
@jsmylnycky 
I have fixed this, but I didn't use the padding: 0 30px, as on this modal we use md-tabs with md-virtual-repeat-container that has inner vertical scrolling . Please review the above commit.

**Comment by jsmylnycky** [comment]
:+1:  assuming the buttons are no longer partially hidden by the updates

**Comment by darushka** [comment]
@jsmylnycky 
What is the issue with hidden buttons?

**Comment by jsmylnycky** [comment]
@darushka  If you go into the alerts modal on production right now (especially one that has a list of alerts)...the buttons are pushed down and only the tops of them are visible.

**Comment by darushka** [comment]
@jsmylnycky 
In my testing url everything worked as expected. It was caused by the latest libraries upgrades.

**Comment by jsmylnycky** [comment]
@darushka  Correct.  I just wanted to make sure that its resolved in this PR since it'll probably be the next release for peach.css to go live.

**Comment by jsmylnycky** [comment]
@darushka  Merge please

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/f1e0025688b51fe49788ba395394357c96ccf41b

**Comment by jsmylnycky** [comment]
v0.3.2 released

**Pull request closed without merging**
