### PR TITLE
fixied display of buttons in card header

### PR DESCRIPTION
**Pull request by darushka**
This PR fixes placement of buttons in Card Header.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:  Let me know when it gets QA'd

**Comment by jsmylnycky** [comment]
@darushka  please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/8e56baa9273b35e6bd57a5dbc87e4e25c4d36bbb

**Comment by jsmylnycky** [comment]
Released v0.2.4

**Pull request closed without merging**
