### PR TITLE
Card 1244 further customization of form fields

### PR DESCRIPTION
**Pull request by darushka**
Update form styles (CARD-1244).
Moved toolbar, sidenav, usermenu, notice, apps-menu, alert styles to Peach-AppRunner (CARD-1277).
Fixed report description being cut off  (CARD-1474).
Chrome - List view not working while Edit Mode is off (CARD-1438)

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by rwrzesien** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@darushka  please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/efee1c896183ba87a2d464e779be1d8a9d39788c

**Comment by jsmylnycky** [comment]
v0.6.0

**Pull request closed without merging**
