### PR TITLE
Implement CUST-2307 switches color

### PR DESCRIPTION
**Pull request by rwrzesien**
This should implement:
https://whentomanage.atlassian.net/browse/CUST-2307

QA verified in ticket.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by jsmylnycky** [comment]
Please merge squash

**Comment by rwrzesien** [comment]
@jsmylnycky Merged and pushed:
5afcfd27fedbf3a0000d5f46f778105ada5a1e42

**Comment by jsmylnycky** [comment]
Released v0.4.5

**Pull request closed without merging**
