### PR TITLE
Cust 1659 fix flash of magnifying icon

### PR DESCRIPTION
**Pull request by darushka**
This PR fixes flashing issue with Magnifying Glass icon when closing search.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@darushka Marge squash this please

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/cb1680431a7a1662dc88532d30ab766b71a276e5

**Comment by jsmylnycky** [comment]
v0.1.24

**Pull request closed without merging**
