### PR TITLE
Cust 1723 add print styling

### PR DESCRIPTION
**Pull request by darushka**
This PR adds styling to print version for v2 pages. Also fixes print version of modals for apps which are using legacy code.

### CODE REVIEW

**Comment by darushka** [comment]
@jsmylnycky 
Sarah wants to test it on staging, as we have problems with Whisk modals preview on dev. Could we release this to staging? May be I can pull the latest master updates to this branch and just release branch?

**Comment by jsmylnycky** [comment]
@darushka If you can setup a branch on web2 to serve it out of the /tmp directory, sure

**Comment by jsmylnycky** [comment]
:+1:

**Comment by rwrzesien** [comment]
@darushka Does it works also without '!important(s)' or they are necessary ?

**Comment by jsmylnycky** [comment]
@rwrzesien  I spoke with Darya and she did need them.  Since they're isolated to the print media type, I'm not too concerned about them.

@darushka  Please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/92378541a05a3798783feefcafc10e653c5c34e3

**Comment by jsmylnycky** [comment]
Releasing with 0.2.7

**Pull request closed without merging**
