### PR TITLE
Added default user profile image for global nav

### PR DESCRIPTION
**Pull request by darushka**
CARD-681 Prod - Global Nav - Missing default thumb nail image
https://peachworks.leankit.com/Boards/View/267929177/287230625

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by jsmylnycky** [comment]
please merge squash

**Comment by rynomars** [comment]
:+1:

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/cb5be56a98e4c61bd77e6409947d3de46997ef85

**Comment by jsmylnycky** [comment]
v0.5.1

**Pull request closed without merging**
