### PR TITLE
Fix for CARD-1631

### PR DESCRIPTION
**Pull request by darushka**
This is minor fix to make icon in chip remove button vertically aligned.

### CODE REVIEW

**Comment by rynomars** [comment]
:+1:

**Comment by jsmylnycky** [comment]
:+1:  please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/191ae207f2b8739235290ce56343b71ddc61e7c7

**Comment by jsmylnycky** [comment]
v0.6.1

**Pull request closed without merging**
