### PR TITLE
applied correct padding to card header and content

### PR DESCRIPTION
**Pull request by darushka**
Updated padding in card header and content according to Dylan comment to issue https://whentomanage.atlassian.net/browse/CUST-2010

### CODE REVIEW

**Comment by jsmylnycky** [comment]
@darushka Please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/f524be5991cb46464fddd84f2850dbb4e331dec6

**Comment by rynomars** [comment]
:thumbsup:

**Comment by rwrzesien** [comment]
:+1:

**Comment by jsmylnycky** [comment]
Released v0.3.0

**Pull request closed without merging**
