### PR TITLE
Fix Alert modal to fit the page

### PR DESCRIPTION
**Pull request by darushka**
This PR solves the issue https://whentomanage.atlassian.net/browse/CUST-2141

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by rwrzesien** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@darushka please merge squash

**Comment by jsmylnycky** [comment]
@darushka please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/ff15e07cbfd104489ede2ef02c4f266eed6168a3

**Comment by jsmylnycky** [comment]
v0.4.6

**Pull request closed without merging**
