### PR TITLE
Card 824 display number of unread alerts

### PR DESCRIPTION
**Pull request by darushka**

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by mbebas** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/7efa433dcc6136f6a2ed0db3cef4a3187667ffc9

**Comment by jsmylnycky** [comment]
v0.5.2

**Pull request closed without merging**
