### PR TITLE
Fixed placement of buttons on Alerts modal when it is opened from Dashboard app

### PR DESCRIPTION
**Pull request by darushka**
This PR solves issue https://whentomanage.atlassian.net/browse/CUST-2269

### CODE REVIEW

**Comment by rynomars** [comment]
:+1:

**Comment by jsmylnycky** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@darushka  please merge squash, this just got QA approval

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/e2d0153e1bfc8e42d98e47dfc852ccbe811459c8

**Comment by jsmylnycky** [comment]
Released v0.4.5

**Pull request closed without merging**
