### PR TITLE
Cust 2232 v2 cake select location pop does not go away

### PR DESCRIPTION
**Pull request by rwrzesien**
This should fix margin issue for:
https://whentomanage.atlassian.net/browse/CUST-2232

### CODE REVIEW

**Comment by jsmylnycky** [comment]
I dont see anything fixed here.  The only two files updated were the dist ones.

**Comment by rwrzesien** [comment]
@jsmylnycky I got somehow confused on this one, branch is updated now and tested.

**Comment by jsmylnycky** [comment]
Not really a fan of the !important, to be honest.  Aren't you able to string together a more accurate CSS target that would trump the Material one?

**Comment by rwrzesien** [comment]
@jsmylnycky Changed styles not to use !important

**Comment by jsmylnycky** [comment]
@rwrzesien  Much better, but that would end up overriding all rules globally that have that rule attached to it.  Please add in something to make it more targeted to the specific peach element instead.

**Comment by rwrzesien** [comment]
@jsmylnycky Updated, I have checked and this one matches correctly as well as does not override other styles.

**Comment by jsmylnycky** [comment]
:+1:  Thanks, please merge squash

**Comment by jsmylnycky** [comment]
Already merged it to get it out.... v0.4.3

**Comment by jsmylnycky** [comment]
Deployment succeeded for Peach-Web2 on deployment id d-11FZV17HC

Deployment data: 
{
    "commit_id": "823fa7a5e619679f66e6f472498ef8e185a26a13", 
    "environment": "production", 
    "description": "v0.5.3", 
    "success": true, 
    "deploy_id": "d-11FZV17HC", 
    "error_message": null, 
    "user_name": "jsmylnycky", 
    "app": "Peach-Web2", 
    "deploy_data": {
        "Failed": 0, 
        "InProgress": 0, 
        "Skipped": 0, 
        "Succeeded": 2, 
        "Pending": 0
    }
}

**Pull request closed without merging**
