### PR TITLE
This implements changes for CUST-2015

### PR DESCRIPTION
**Pull request by rwrzesien**
This fixes:
https://whentomanage.atlassian.net/browse/CUST-2015

QA verified.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@rwrzesien Please merge squash

**Comment by rwrzesien** [comment]
@jsmylnycky Merged and pushed, commit:
4c4a19639a72ecd00efa2975de90e0d9d2dcd7bc

**Comment by rynomars** [comment]
:thumbsup:

**Comment by jsmylnycky** [comment]
Trying to wait for #41 to get approved to consolidate the updates.

**Comment by jsmylnycky** [comment]
Released v0.3.5

**Pull request closed without merging**
