### PR TITLE
Card 2219 location selector bugs on mobile

### PR DESCRIPTION
**Pull request by PSkierniewski**
Peach select - added smooth scroll

### CODE REVIEW

**Comment by jsmylnycky** [comment]
👍

**Comment by againsley** [comment]
👍 on this. I'd like to merge this once peach.css is ready https://github.com/peachworks/peach_panlogv2/pull/20

**Comment by rynomars** [comment]
👍

**Comment by jsmylnycky** [comment]
v0.6.2

**Pull request closed without merging**
