### PR TITLE
fixed styling of all apps icon

### PR DESCRIPTION
**Pull request by darushka**
This PR makes All Apps icon positioned right after apps with a free space between it and Config icon.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by jsmylnycky** [comment]
merge squash please

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/peach.css/commit/f8def666df777c3e34655b83a576608fd39aee29

**Comment by jsmylnycky** [comment]
Released v0.1.22

**Pull request closed without merging**
