### PR TITLE
CUST-1161 Page Modals

### PR DESCRIPTION
**Pull request by jsmylnycky**
This supports https://github.com/peachworks/ngPeach/pull/10

### CODE REVIEW

**Comment by mbebas** [comment]
:+1: 
@jsmylnycky just a general question - why z index starts from 60? Just curious, if this is for example - because angular material uses z-indexes from 0 to 60 :)

**Comment by jsmylnycky** [comment]
@mbebas I was just trying to keep it as close to the material zindex as possible.  I should probably change those ones that are setting 7777, 8888 and 9999 to be closer as well...

**Comment by mbebas** [comment]
I was guessing so, you just confirmed :) Ok thanks.

**Comment by darushka** [comment]
:+1

**Comment by againsley** [comment]
:+1:

If we have some rules around what z-indexes to use let's make sure they get into the style guide.

**Comment by jsmylnycky** [comment]
@againsley  Agreed,  we'll want to go through and review the z-indexes (indices?).  Definitely would prefer to hover around 60 for "modal" type of functionality that pops over everything to keep in line with Material's use.  I added a comment on CUST-1300 about it.

**Comment by jsmylnycky** [comment]
Released: 0dd3ed5    v0.0.57

**Pull request closed without merging**
